### PR TITLE
upgrade provider to work w/ most recent release of koop-server

### PR DESCRIPTION
**Pull request by jgravois**
restructure routes
new convention for inheriting from base controller and model
get rid of provider config, since it seems to be ignored
processFeatureServer is now a public method in BaseController
utilize koop.Cache
no more globals

### CODE REVIEW

**Comment by jgravois** [comment]
just out of curiousity, did you test against my forked feature branch first?

**Comment by nixta** [comment]
I did not, but I saw you test it.

**Comment by jgravois** [comment]
awesome.  you probably already know this, but pointing at the forked version pre-merge and installing on a clean koop clone to inspect is actually a lot more convenient than i thought it would be.  

happy to chat about it more whenever if it'd be helpful.

**Comment by nixta** [comment]
Yep. It would be. Got some other stuff in the pipeline before I can dive back into Koop, but then I'll be bothering you until you're sick of me.

**Pull request merged**
